// controllers/taskController.js
const mongoose = require('mongoose');
const Task = require('../models/Task');
const User = require('../models/User');

// ✅ WhatsApp helpers (Baileys)
const { sendText } = require('../utils/baileysClient');

// ✉️ Email helpers
const { sendEmail, renderTemplate } = require('../utils/email');

/* Helpers */
const STATUS_MAP = {
  'todo': 'To Do','to do': 'To Do','to-do': 'To Do',
  'inprogress': 'In Progress','in-progress': 'In Progress','in progress': 'In Progress',
  'done':'Done','completed':'Done','complete':'Done'
};
const normalizeStatus = (raw) => {
  if (raw === undefined || raw === null) return null;
  const key = String(raw).trim().toLowerCase();
  return STATUS_MAP[key] || null;
};

function isArrayOfObjectIds(arr) {
  return Array.isArray(arr) && arr.every(id => mongoose.Types.ObjectId.isValid(id));
}

const populateAssignees = (query) => query.populate('assignees', 'name email phone profileImageUrl');
const enrichTaskDoc = (t) => {
  const task = { ...t };

  const subtasks = Array.isArray(task.subtasks) ? task.subtasks : [];
  const completedSubtaskCount = subtasks.filter(st => !!st.isDone).length;
  const totalSubtasks = subtasks.length;
  task.CompletedSubtaskCount = completedSubtaskCount;

  const todoChecklist = Array.isArray(task.todoChecklist) ? task.todoChecklist : [];
  task.todoChecklist = todoChecklist;
  task.checklistCount = todoChecklist.length;

  task.progress = totalSubtasks > 0
    ? Math.round((completedSubtaskCount / totalSubtasks) * 100)
    : (task.progress || 0);

  task.assignees = Array.isArray(task.assignees) ? task.assignees : [];

  return task;
};

/* Derive status from todoChecklist if present; else subtasks; else fallback */
const deriveStatusFromTask = (task) => {
  const todo = Array.isArray(task.todoChecklist) ? task.todoChecklist : null;
  if (todo && todo.length > 0) {
    const doneCount = todo.filter(i => !!i.completed).length;
    if (doneCount === todo.length) return 'Done';
    if (doneCount > 0) return 'In Progress';
    return 'To Do';
  }
  const subs = Array.isArray(task.subtasks) ? task.subtasks : [];
  if (subs.length > 0) {
    const doneCount = subs.filter(s => !!s.isDone).length;
    if (doneCount === subs.length) return 'Done';
    if (doneCount > 0) return 'In Progress';
    return 'To Do';
  }
  return task.status || 'To Do';
};

/* ------------------------ WhatsApp: helpers ------------------------ */
/**
 * Nicely formatted WhatsApp notifications to all assignees for a newly created task.
 */
async function notifyTaskCreate(taskId) {
  try {
    const t = await Task.findById(taskId)
      .populate('assignees', 'name phone')
      .populate('project', 'title')
      .lean();

    if (!t) {
      console.warn(`[notifyTaskCreate] Task ${taskId} not found`);
      return;
    }

    const projectTitle = t.project?.title || 'General';
    // Format: 17-Sep-25 09:07 PM (IST)
    const dueStr = t.dueDate
      ? new Date(t.dueDate).toLocaleString('en-GB', {
          timeZone: 'Asia/Kolkata',
          day: '2-digit',
          month: 'short',
          year: '2-digit',
          hour: '2-digit',
          minute: '2-digit',
          hour12: true
        }).replace(',', '')
      : 'N/A';

    const appUrl = process.env.APP_PUBLIC_URL || process.env.CLIENT_URL || '';

    console.log(`[notifyTaskCreate] Task created: ${t.title}, Assignees: ${t.assignees?.length || 0}`);

    for (const u of (t.assignees || [])) {
      if (!u?.phone) {
        console.warn(`[notifyTaskCreate] Assignee ${u?.name || 'Unknown'} (${u?._id}) has no phone number`);
        continue;
      }

      const lines = [
        `👋 *Dear ${u.name || 'User'}*,`,
        ``,
        `You have been *assigned a new task*.`,
        ``,
        `*Category* - ${projectTitle}`,
        `*Task* - ${t.title}`,
      ];
      if (t.description) lines.push(`*Description* - ${t.description}`);
      if (t.priority) lines.push(`*Priority* - ${t.priority}`);
      lines.push(`*Due Date* - ${dueStr}`);
      if (appUrl) lines.push(``, `🔗 *Open App* - ${appUrl}`);
      lines.push(``, `_This is an automated notification generated by your Task Manager._`, `Please do not reply`);

      const body = lines.join('\n');

      console.log(`[notifyTaskCreate] Sending WhatsApp to ${u.phone} (${u.name})`);
      await sendText(u.phone, body)
        .then(() => console.log(`[notifyTaskCreate] ✅ sent to ${u.phone}`))
        .catch(e => console.error(`[notifyTaskCreate] ❌ failed ${u.phone}:`, e.message));
    }
  } catch (err) {
    console.error('[notifyTaskCreate] Error:', err.message);
  }
}

/* ------------------------ Email: helpers ------------------------ */
async function notifyTaskCreateEmail(taskId) {
  try {
    const t = await Task.findById(taskId)
      .populate('assignees', 'name email')
      .populate('project', 'title')
      .lean();
    if (!t) return;

    const projectTitle = t.project?.title || 'Project';
    const due = t.dueDate ? new Date(t.dueDate).toDateString() : 'N/A';

    for (const u of (t.assignees || [])) {
      if (!u?.email) continue;
      const html = renderTemplate('taskAssigned.html', {
        name: u.name || 'there',
        project: projectTitle,
        title: t.title,
        dueDate: due,
        descriptionSection: t.description ? `<p><strong>Description:</strong> ${t.description}</p>` : ''
      });
      await sendEmail(
        u.email,
        `[Task Assigned] ${t.title} (${projectTitle})`,
        html
      ).catch(e => console.error('sendEmail task create error:', e.message));
    }
  } catch (err) {
    console.error('notifyTaskCreateEmail error:', err.message);
  }
}

/**
 * Send assignment emails only to newly-added assignees when task is updated.
 */
async function notifyNewAssigneesEmail(taskId, newAssigneeIds = []) {
  if (!newAssigneeIds?.length) return;
  try {
    const t = await Task.findById(taskId)
      .populate({ path: 'assignees', select: 'name email', match: { _id: { $in: newAssigneeIds } } })
      .populate('project', 'title')
      .lean();
    if (!t) return;

    const projectTitle = t.project?.title || 'Project';
    const due = t.dueDate ? new Date(t.dueDate).toDateString() : 'N/A';

    for (const u of (t.assignees || [])) {
      if (!u?.email) continue;
      const html = renderTemplate('taskAssigned.html', {
        name: u.name || 'there',
        project: projectTitle,
        title: t.title,
        dueDate: due,
        descriptionSection: t.description ? `<p><strong>Description:</strong> ${t.description}</p>` : ''
      });
      await sendEmail(
        u.email,
        `[Task Assigned] ${t.title} (${projectTitle})`,
        html
      ).catch(e => console.error('sendEmail new assignee error:', e.message));
    }
  } catch (err) {
    console.error('notifyNewAssigneesEmail error:', err.message);
  }
}

/* ------------------------ Controllers ------------------------ */

const getTasks = async (req, res) => {
  try {
    const wantOnlyAssigned = String(req.query.onlyAssigned || '').toLowerCase() === 'true';
    const projectId = req.query.project;

    const filter = {};
    if (projectId && mongoose.Types.ObjectId.isValid(projectId)) {
      filter.project = projectId;
      if (wantOnlyAssigned) filter.assignees = req.user._id;
    } else {
      if (wantOnlyAssigned || !projectId) filter.assignees = req.user._id;
    }

    let q = Task.find(filter).lean();
    q = populateAssignees(q);
    const tasks = await q;
    const tasksWithCounts = tasks.map(enrichTaskDoc);
    return res.json({ tasks: tasksWithCounts });
  } catch (err) {
    console.error('getTasks error:', err);
    return res.status(500).json({ message: 'Server error', error: err.message });
  }
};

const getTaskById = async (req, res) => {
  try {
    if (!mongoose.Types.ObjectId.isValid(req.params.id)) return res.status(400).json({ message: 'Invalid task id' });
    let q = Task.findById(req.params.id).lean();
    q = populateAssignees(q);
    const task = await q;
    if (!task) return res.status(404).json({ message: 'Task not found' });

    const enriched = enrichTaskDoc(task);
    return res.json({ task: enriched });
  } catch (err) {
    console.error('getTaskById error:', err);
    return res.status(500).json({ message: 'Server error', error: err.message });
  }
};

const createTask = async (req, res) => {
  try {
    let {
      title,
      description,
      status,
      priority,
      project,
      dueDate,
      assignees = [],
      attachments = [],
      subtasks = [],
      dependencies = [],
      todoChecklist = []
    } = req.body;

    if (!title) return res.status(400).json({ message: 'Title is required' });

    // Normalize incoming assignees
    if (!Array.isArray(assignees)) assignees = assignees ? [assignees] : [];
    assignees = assignees.map(String).filter(Boolean);

    // Validate objectId shape
    if (assignees.length > 0 && !isArrayOfObjectIds(assignees)) {
      return res.status(400).json({ message: 'assignees must be array of valid user IDs' });
    }

    // OPTIONAL: ensure users exist
    if (assignees.length > 0) {
      const found = await User.find({ _id: { $in: assignees } }).select('_id').lean();
      const foundIds = new Set(found.map(f => String(f._id)));
      const missing = assignees.filter(id => !foundIds.has(String(id)));
      if (missing.length > 0) {
        return res.status(400).json({ message: 'Some assignees not found', missing });
      }
    }

    // Normalize & derive
    const normalizedStatus = normalizeStatus(status) || 'To Do';
    if (todoChecklist && !Array.isArray(todoChecklist)) todoChecklist = [];
    todoChecklist = todoChecklist.map(x => {
      const obj = typeof x === 'object' && x !== null ? x : { text: String(x || ''), completed: false };
      return { text: String(obj.text || ''), completed: !!obj.completed };
    }).filter(Boolean);

    if (!Array.isArray(subtasks)) subtasks = [];

    const taskData = {
      title,
      description,
      priority,
      project,
      dueDate,
      assignees,
      attachments: Array.isArray(attachments) ? attachments : [],
      subtasks,
      dependencies: Array.isArray(dependencies) ? dependencies : [],
      todoChecklist,
      status: normalizedStatus
    };

    const task = await Task.create(taskData);

    // 📣 Notify: WhatsApp + Email
    console.log(`[createTask] Task created with ID: ${task._id}, initiating notifications...`);
    notifyTaskCreate(task._id).catch(e => console.error('[createTask] notifyTaskCreate error:', e.message));
    notifyTaskCreateEmail(task._id).catch(e => console.error('[createTask] notifyTaskCreateEmail error:', e.message));

    const populated = await populateAssignees(Task.findById(task._id)).lean();
    const enriched = enrichTaskDoc(populated);
    return res.status(201).json({ message: 'Task created', task: enriched });
  } catch (err) {
    console.error('[createTask] error:', err);
    return res.status(500).json({ message: 'Server error', error: err.message });
  }
};

const updateTask = async (req, res) => {
  try {
    if (!mongoose.Types.ObjectId.isValid(req.params.id)) return res.status(400).json({ message: 'Invalid task id' });
    const task = await Task.findById(req.params.id);
    if (!task) return res.status(404).json({ message: 'Task not found' });

    // capture old assignees for email diff
    const __oldAssigneesForEmail = Array.isArray(task.assignees) ? task.assignees.map(a => String(a)) : [];

    const fields = ['title','description','priority','project','dueDate','attachments'];
    fields.forEach(f => { if (req.body[f] !== undefined) task[f] = req.body[f]; });

    // handle assignees
    if (req.body.assignees !== undefined) {
      if (!isArrayOfObjectIds(req.body.assignees)) return res.status(400).json({ message: 'assignees must be array of user IDs' });
      task.assignees = req.body.assignees;
    }

    // handle todoChecklist (new)
    if (req.body.todoChecklist !== undefined) {
      if (!Array.isArray(req.body.todoChecklist)) return res.status(400).json({ message: 'todoChecklist must be an array' });
      task.todoChecklist = req.body.todoChecklist.map(i => {
        const obj = typeof i === 'object' && i !== null ? i : { text: String(i || ''), completed: false };
        return { text: String(obj.text || ''), completed: !!obj.completed };
      }).filter(Boolean);
      task.checklistCount = task.todoChecklist.length;

      // derive status from todoChecklist
      task.status = deriveStatusFromTask(task);
    }

    // handle subtasks (legacy)
    if (req.body.subtasks !== undefined) {
      const subs = Array.isArray(req.body.subtasks) ? req.body.subtasks : [];
      task.subtasks = subs.map(s => {
        const o = typeof s === 'object' && s !== null ? s : { title: String(s || ''), isDone: false };
        return { title: String(o.title || ''), isDone: !!o.isDone, assignees: Array.isArray(o.assignees) ? o.assignees : [] };
      });
      // recompute progress
      const doneCount = task.subtasks.filter(x => !!x.isDone).length;
      task.progress = task.subtasks.length ? Math.round((doneCount / task.subtasks.length) * 100) : (task.progress || 0);
      // derive status again
      task.status = deriveStatusFromTask(task);
    }

    // handle status direct update (optional)
    if (req.body.status !== undefined) {
      const normalized = normalizeStatus(req.body.status);
      if (!normalized) return res.status(400).json({ message: `Invalid status: ${req.body.status}` });
      task.status = normalized;
      if (normalized === 'Done') { (task.subtasks || []).forEach(s => s.isDone = true); task.progress = 100; }
    }

    // handle dependencies
    if (req.body.dependencies !== undefined) {
      if (!isArrayOfObjectIds(req.body.dependencies)) return res.status(400).json({ message: 'dependencies must be array of task IDs' });
      task.dependencies = req.body.dependencies;
    }

    await task.save();

    // ✉️ Email: notify only newly added assignees
    try {
      const _new = Array.isArray(task.assignees) ? task.assignees.map(a => String(a)) : [];
      const justAdded = _new.filter(id => !__oldAssigneesForEmail.includes(String(id)));
      if (justAdded.length) await notifyNewAssigneesEmail(task._id, justAdded);
    } catch(e) { console.error('notifyNewAssigneesEmail error:', e.message); }

    const populated = await populateAssignees(Task.findById(task._id)).lean();
    const enriched = enrichTaskDoc(populated);
    return res.json({ message: 'Task updated', task: enriched });
  } catch (err) {
    console.error('updateTask error:', err);
    return res.status(500).json({ message: 'Server error', error: err.message });
  }
};

const deleteTask = async (req, res) => {
  try {
    if (!mongoose.Types.ObjectId.isValid(req.params.id)) return res.status(400).json({ message: 'Invalid task id' });
    const task = await Task.findById(req.params.id);
    if (!task) return res.status(404).json({ message: 'Task not found' });
    await task.deleteOne();
    return res.json({ message: 'Task deleted' });
  } catch (err) {
    console.error('deleteTask error:', err);
    return res.status(500).json({ message: 'Server error', error: err.message });
  }
};

const updateTaskStatus = async (req, res) => {
  try {
    if (!mongoose.Types.ObjectId.isValid(req.params.id)) return res.status(400).json({ message: 'Invalid task id' });
    const task = await Task.findById(req.params.id);
    if (!task) return res.status(404).json({ message: 'Task not found' });

    const normalized = normalizeStatus(req.body.status);
    if (!normalized) return res.status(400).json({ message: `Invalid status: ${req.body.status}` });
    task.status = normalized;
    if (normalized === 'Done') { (task.subtasks || []).forEach(s => s.isDone = true); task.progress = 100; }

    await task.save();

    const populated = await populateAssignees(Task.findById(task._id)).lean();
    const enriched = enrichTaskDoc(populated);
    return res.json({ message: 'Task status updated', task: enriched });
  } catch (err) {
    console.error('updateTaskStatus error:', err);
    return res.status(500).json({ message: 'Server error', error: err.message });
  }
};

/* --------- Subtasks / Dependencies (unchanged logic condensed) --------- */
const addSubtask = async (req, res) => {
  try {
    if (!mongoose.Types.ObjectId.isValid(req.params.id)) return res.status(400).json({ message: 'Invalid task id' });
    const { title = '', isDone = false, assignees = [] } = req.body;
    const task = await Task.findById(req.params.id);
    if (!task) return res.status(404).json({ message: 'Task not found' });
    task.subtasks.push({ title, isDone: !!isDone, assignees: Array.isArray(assignees) ? assignees : [] });
    task.status = deriveStatusFromTask(task);
    const doneCount = task.subtasks.filter(x => !!x.isDone).length;
    task.progress = task.subtasks.length ? Math.round((doneCount / task.subtasks.length) * 100) : (task.progress || 0);
    await task.save();
    const populated = await populateAssignees(Task.findById(task._id)).lean();
    const enriched = enrichTaskDoc(populated);
    return res.status(201).json({ message: 'Subtask added', task: enriched });
  } catch (err) {
    console.error('addSubtask error:', err);
    return res.status(500).json({ message: 'Server error', error: err.message });
  }
};

const updateSubtask = async (req, res) => {
  try {
    const { title, isDone, assignees } = req.body;
    const task = await Task.findById(req.params.id);
    if (!task) return res.status(404).json({ message: 'Task not found' });
    const sub = task.subtasks.id(req.params.subId);
    if (!sub) return res.status(404).json({ message: 'Subtask not found' });
    if (title !== undefined) sub.title = title;
    if (isDone !== undefined) sub.isDone = !!isDone;
    if (assignees !== undefined) {
      if (!isArrayOfObjectIds(assignees)) return res.status(400).json({ message: 'assignees must be array of user IDs' });
      sub.assignees = assignees;
    }
    task.status = deriveStatusFromTask(task);
    const doneCount = task.subtasks.filter(x => !!x.isDone).length;
    task.progress = task.subtasks.length ? Math.round((doneCount / task.subtasks.length) * 100) : (task.progress || 0);
    await task.save();
    const populated = await populateAssignees(Task.findById(task._id)).lean();
    const enriched = enrichTaskDoc(populated);
    return res.json({ message: 'Subtask updated', task: enriched });
  } catch (err) {
    console.error('updateSubtask error:', err);
    return res.status(500).json({ message: 'Server error', error: err.message });
  }
};

const deleteSubtask = async (req, res) => {
  try {
    const task = await Task.findById(req.params.id);
    if (!task) return res.status(404).json({ message: 'Task not found' });
    const sub = task.subtasks.id(req.params.subId);
    if (!sub) return res.status(404).json({ message: 'Subtask not found' });
    sub.deleteOne();
    task.status = deriveStatusFromTask(task);
    const doneCount = task.subtasks.filter(x => !!x.isDone).length;
    task.progress = task.subtasks.length ? Math.round((doneCount / task.subtasks.length) * 100) : (task.progress || 0);
    await task.save();
    const populated = await populateAssignees(Task.findById(task._id)).lean();
    const enriched = enrichTaskDoc(populated);
    return res.json({ message: 'Subtask deleted', task: enriched });
  } catch (err) {
    console.error('deleteSubtask error:', err);
    return res.status(500).json({ message: 'Server error', error: err.message });
  }
};

const addDependency = async (req, res) => {
  try {
    const { dependsOn } = req.body;
    if (!mongoose.Types.ObjectId.isValid(req.params.id)) return res.status(400).json({ message: 'Invalid task id' });
    if (!mongoose.Types.ObjectId.isValid(dependsOn)) return res.status(400).json({ message: 'Invalid dependency id' });
    const task = await Task.findById(req.params.id);
    if (!task) return res.status(404).json({ message: 'Task not found' });
    task.dependencies = Array.isArray(task.dependencies) ? task.dependencies : [];
    if (!task.dependencies.find(x => String(x) === String(dependsOn))) task.dependencies.push(dependsOn);
    await task.save();
    return res.status(201).json({ message: 'Dependency added' });
  } catch (err) {
    console.error('addDependency error:', err);
    return res.status(500).json({ message: 'Server error', error: err.message });
  }
};

const updateDependency = async (req, res) => {
  try {
    const { depId } = req.params;
    if (!mongoose.Types.ObjectId.isValid(req.params.id)) return res.status(400).json({ message: 'Invalid task id' });
    if (!mongoose.Types.ObjectId.isValid(depId)) return res.status(400).json({ message: 'Invalid dependency id' });
    const task = await Task.findById(req.params.id);
    if (!task) return res.status(404).json({ message: 'Task not found' });
    task.dependencies = (task.dependencies || []).filter(x => String(x) !== String(depId));
    await task.save();
    return res.json({ message: 'Dependency removed' });
  } catch (err) {
    console.error('updateDependency error:', err);
    return res.status(500).json({ message: 'Server error', error: err.message });
  }
};

const getDashboardData = async (req, res) => {
  try {
    const tasks = await Task.find({}).lean();
    const totalTasks = tasks.length;
    const doneTasks = tasks.filter(t => deriveStatusFromTask(t) === 'Done').length;
    const inProgressTasks = tasks.filter(t => deriveStatusFromTask(t) === 'In Progress').length;
    const todoTasks = totalTasks - doneTasks - inProgressTasks;

    const priorities = { Low: 0, Medium: 0, High: 0, Critical: 0 };
    tasks.forEach(t => { priorities[t.priority] = (priorities[t.priority] || 0) + 1; });

    return res.json({
      totals: { totalTasks, todoTasks, inProgressTasks, doneTasks },
      taskPriorityLevels: priorities
    });
  } catch (err) {
    console.error('getDashboardData error:', err);
    return res.status(500).json({ message: 'Server error', error: err.message });
  }
};

const getUserDashboardData = async (req, res) => {
  try {
    const uid = req.user?._id;
    const tasks = await Task.find({ assignees: uid }).lean();

    const overdueTasks = tasks.filter(t => t.dueDate && new Date(t.dueDate) < new Date() && deriveStatusFromTask(t) !== 'Done').length;

    const priorities = { Low: 0, Medium: 0, High: 0, Critical: 0 };
    tasks.forEach(t => { priorities[t.priority] = (priorities[t.priority] || 0) + 1; });

    return res.json({
      inProgressTasks: tasks.filter(t => deriveStatusFromTask(t) === 'In Progress').length,
      completedTasks: tasks.filter(t => deriveStatusFromTask(t) === 'Done').length,
      overdueTasks,
      charts: { taskPriorityLevels: priorities }
    });
  } catch (err) {
    console.error('getUserDashboardData error:', err);
    return res.status(500).json({ message: 'Server error', error: err.message });
  }
};

module.exports = {
  getTasks, getTaskById, createTask, updateTask, deleteTask, updateTaskStatus,
  addSubtask, updateSubtask, deleteSubtask, addDependency, updateDependency,
  getDashboardData, getUserDashboardData
};
